services:
    frontend:
        container_name: frontend
        build: ./frontend
        volumes:
            - ./frontend:/usr/src/app
        ports:
            - 3000:3000
        command: bash -c "npm start"
    backend:
        depends_on:
            - db
        container_name: backend
        build: ./backend
        ports:
            - 8080:8080
            - 19820:1980
            - 8021:8021
        volumes:
            - ./Extensions:/usr/local/zope/ZopeInstance/Extensions
            - ./backend/data:/usr/local/zope/ZopeInstance/var
            - ./backend/GlobalModules:/usr/local/zope/ZopeInstance/Products/GlobalModules
            - ./backend/zopeConf:/usr/local/zope/ZopeInstance/etc
        # example of psycopg connection string: dbname=postgres user=postgres password=example host=db port=5432
        # command: >
        #     bash -c "/usr/local/zope/ZopeInstance/bin/zopectl start"
    db:
        build: ./db
        container_name: db
        restart: always
        ports:
            - 25643:5432
        volumes:
            - postgres:/var/lib/postgresql/data
            #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            POSTGRES_PASSWORD: example

volumes:
    postgres:
#     pgadmin:
